# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  monitoringapi:
    image: monitoringapi
    build:
      context: .
      dockerfile: MonitoringApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5009:5009
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
